In [3]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np
corpus = [
    'This is the first document.',
    'This document is the second document.',
    'And this is the third one.',
    'Is this the first document?',
]
vectorizer = CountVectorizer(binary = True)
X = vectorizer.fit_transform(corpus)
print(vectorizer.get_feature_names())

print(X.toarray())

['and', 'document', 'first', 'is', 'one', 'second', 'the', 'third', 'this']
[[0 1 1 1 0 0 1 0 1]
 [0 1 0 1 0 1 1 0 1]
 [1 0 0 1 1 0 1 1 1]
 [0 1 1 1 0 0 1 0 1]]


In [12]:
index = [0,1]

In [26]:
A = np.sum(X[index], axis=0)
A

matrix([[0, 2, 1, 2, 0, 1, 2, 0, 2]], dtype=int64)

In [27]:
B = X[index].shape[0]-np.sum(X[index], axis=0)
B

matrix([[2, 0, 1, 0, 2, 1, 0, 2, 0]], dtype=int64)

In [28]:
A.A*B.A

array([[0, 0, 1, 0, 0, 1, 0, 0, 0]], dtype=int64)